PRAGMA auto_vacuum = FULL;
CREATE TABLE PERSON (FIRSTNAME VARCHAR2(25), LASTNAME VARCHAR2(25));

INSERT INTO PERSON (FIRSTNAME,LASTNAME) VALUES ('Joe','Smith');
INSERT INTO PERSON (FIRSTNAME,LASTNAME) VALUES ('Frank','Anderson');
INSERT INTO PERSON (FIRSTNAME,LASTNAME) VALUES ('Martha','Little');